//====SORTEADOR DE NOMES====
let nomes = [
  "AMANDA TAÍSA AMADO AMARO",
  "ANA CLARA DA SILVA LOPES",
  "ARTHUR DE AVILA VELHO",
  "ARTHUR MIGUEL MACHADO GOMES",
  "EDUARDO DOS SANTOS PAIM",
  "EMILY TORRES KESSNER",
  "FELIPE KELLER BORILE DE SOUZA",
  "FELIPE SOUZA DE LIMA",
  "IVNE JANALLY NUNES VIEIRA",
  "JOÃO LUCAS CIRINO DOS SANTOS",
  "JOÃO PEDRO CECCHIN DA SILVA",
  "JOÃO PEDRO PEREIRA NICHES",
  "LÍVIA BERTON",
  "LUAN PETERSON COSTA DOS SANTOS",
  "LUÍSA DOS SANTOS LIMA",
  "LUIZ FELIPE SOARES RAMOS",
  "MATHIAS STUMPF BORGES DE ABREU",
  "MATEUS RODRIGUES VACCARI",
  "MATHEUS AUGUSTO RAMIRES AZAMBUJA",
  "MATHEUS MENDES MOREIRA",
  "MAURÍCIO BERNART",
  "NICOLY CECCHIN DA SILVA",
  "OTÁVIO DA SILVA FADANELLI",
  "PEDRO HENRIQUE UBERTI DE LIMA",
  "PIETRA BERNART DA SILVA",
  "PIETRO ANTÔNIO ROSSI MAZZOCHI",
  "PIETRO DANIELI WOLF",
  "SAIMON MACHADO DA SILVA",
  "THAÍS FIORENTINI DA CONCEIÇÃO",
  "VANESSA DE VARGAS SOUZA",
  "VITÓRIA MACHADO VARGAS",
  "WESLEY VENSON",
  "WILLIAN RODRIGUEZ DE ALMEIDA",
  "ZAC FELICIANO FOGAÇA"
];

function sorteio() {
  let nome = Math.floor(Math.random() * nomes.length);
  console.log(`\n${nome + 1}. ${nomes[nome]}\n`);
}

console.log("\n=== SORTEIO DE NOMES ===");
sorteio();



